### ISSUE TITLE
[Bug]: Crash when opening breakfast

### ISSUE THREAD

**Issue by BloodRaven0** [maksimowiczm/FoodYou#72]
### Describe the bug

Hey, I encountered a persistent crash. I added some products (from Open Food Facts) to the breakfast 2 days from now, and every time I try to enter that specific breakfast to edit or delete the products, the app crashes. I don't actually remember which products I added, sorry. I can't enter the menu to see them, and I don't know if the products themselves are what's causing the issue.

I captured a logcat during a crash (since it's reproducible), filtering by Errors only. I's my first time capturing logs, so it might have some irrelevant info, but I hope I captured the info that will help diagnose the problem.
https://pastebin.com/Fs7UnNgK (expires in a month)

### Expected Behavior

Expected behavior is not crashing, lol.

**Comment by maksimowiczm** [comment]
What version are you using? If it's 2.0.0 then it's fixed in the latest update.

You can download the APK from GitHub or wait for the F-Droid release (probably ~1 week). F-Droid and GitHub releases use the same APK files, so you can install from either.

Related to #64, #70

**Comment by BloodRaven0** [comment]
Unfortunately, I already am using the 2.0.0 version, and have been using it all along. So it seems the problem persisted.

I forgot to mention - my device is Samsung Galaxy A54 5G, running Android 13 (oneUI 5.1), if that matters.

If there's anything else I can do to diagnose the problem, let me know.

**Comment by Nikoichu** [comment]
Thank you, updating indeed fixed the issue! ❤️
